bind-key C-a select-window -t 1
bind-key C-s select-window -t 2
bind-key C-d select-window -t 3
bind-key C-f select-window -t 4
bind-key C-g select-window -t 5

set -g base-index 1
set -g pane-base-index 1
set -g mouse on

bind \\ split-window -h
bind - split-window -v
bind r source-file ~/.tmux.conf \; display "Reloaded!"
